### PR TITLE
Generate GL Externs from the Khronos XML Registry

### PR DESCRIPTION
**Pull request by Aidan63**
Hello, recently after manually filling out some of the holes in the generated api (e.g. glMapNamedBufferRange) I decided to have a go at replacing the generator with one which reads from the official openGL xml registry and supports generating files for different opengl versions and api's.

The new generator creates the bindings from the gl.xml file (https://github.com/KhronosGroup/OpenGL-Registry) and by modifying the cli arguments passed to the generator program you can create a extern class for GL, GLES1, and GLES2. You can also set a max gl version and if its a core or compat profile (see the build.hxml for generator options).

I've replaced the GL.hx class with a openGL core 4.6 profile from the generator and I was able to get my projects running on windows and linux with no changes so hopefully it won't break compatibility.

### CODE REVIEW

**Comment by ruby0x1** [comment]
This is interesting, thanks. I'll have to take a closer look, but having the converter be more consistent is a good thing. The only thing I can see that stands out is minor code formatting stuff to be consistent with the linc and snowkit stuff.

It's looking good though! 

(p.s you did a PR off your master branch, which would prevent you from progressing on your own master till merge. Ideally a separate branch is used for PRs!)

**Comment by Aidan63** [comment]
I'll go over the code formatting tomorrow to try and make it more consistent with the other linc libs. I see what you mean with the PR branch, I originally developed the generator in a separate branch but merged it before creating this PR.
Would closing this one and opening another on a separate branch be a good shout if there's still some work to be done?

**Comment by ruby0x1** [comment]
A separate branch (`git checkout -b reg-gen`) isn't too much trouble, if you PR again we'll make a link between the two for tracking purposes. Either is fine, it's more that it doesn't prevent you from other work on master (I guess you could work in a branch too). Since I don't know exactly when I just wanted to point it out so you don't get stuck waiting.

**Comment by Aidan63** [comment]
I've gone through the generators code and made the brace and whitespace styles match the old generator so it should hopefully be more consistent with other linc and snowkit stuff.
Also added a few little things like force importing haxe bytes which I forgot to re-add before.

**Comment by Aidan63** [comment]
Just another little feature, additional extensions can be requested from the cli.

`neko buildgl.n gl 4 4 core GL_ARB_direct_state_access GL_ARB_sparse_texture`

This would produce a GL 4.4 core profile but with the DSA and sparse texture functions and enums included since they're not included in 4.4.

**Pull request closed without merging**
