### PR TITLE
correct count calculation for glUniform2fv

### PR DESCRIPTION
**Pull request by le-doux**
count should be per-vec2, so we take the byteLength (4 bytes * 2 floats * x vec == 8x) and divide by 8 (using >>3) to get the count of vec2s

### CODE REVIEW

**Comment by ruby0x1** [comment]
p.s We'll probably want to correct all of them (`iv` at minimum, and the other uniform*v types) while we're already fixing these.

**Comment by le-doux** [comment]
Agreed. I'm happy to take a look at that later when I have some free time.

**Comment by le-doux** [comment]
Hi @underscorediscovery, I've updated this pull request to work for all the float and integer vector array methods. I switched from bitshifting to division for the calculation, since it's more readable and some of the methods need division by 12, which isn't a power of 2. I can switch the power-of-2 methods back if there's a reason to (perf?).

**Comment by ruby0x1** [comment]
That looks fine to me @le-doux, I'm not sure where I found the original logic but clearer is better. Thanks.

**Pull request merged**
